name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: main }

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with: { override: true }
      - name: Check
        run: cargo check --all-targets --all-features
      - name: Cache for next jobs
        uses: actions/cache@v2
        with:
          key: target-${{ runner.os }}-${{ hashFiles('src/*') }}
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/.git

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
      - name: Grab cache
        uses: actions/cache@v2
        with:
          key: target-${{ runner.os }}-${{ hashFiles('src/*') }}
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/.git
      - name: Test
        run: cargo test --all-targets --all-features --no-fail-fast

  clippy:
    name: Clippy
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
      - name: Grab cache
        uses: actions/cache@v2
        with:
          key: target-${{ runner.os }}-${{ hashFiles('src/*') }}
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/.git
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    name: Fmt
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
      - name: Grab cache
        uses: actions/cache@v2
        with:
          key: target-${{ runner.os }}-${{ hashFiles('src/*') }}
          path: |
            target
            ~/.cargo/registry
            ~/.cargo/.git
      - name: Fmt
        run: cargo fmt -- --check
