name: CI

on:
  push: { branches: [main, master] }
  pull_request: { branches: [main, master] }

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with: { toolchain: stable, override: true }
      - name: Check
        run: cargo check --all-targets --all-features
      - name: Test
        if: always() && steps.Check.outcome == "success"
        run: cargo test --all-targets --all-features --no-fail-fast
      - name: Clippy
        if: always() && steps.Check.outcome == "success"
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Fmt
        if: always() && steps.Check.outcome == "success"
        run: cargo fmt -- --check
